### ISSUE TITLE
Grails 3.0 compatibility

### ISSUE THREAD

**Issue by wwarlock** [grails-plugins/grails-spring-security-ui#35]
Hello, guys.

Do you have plans to migrate that plugin to Grails 3 environment?
May I help you to do that ?

**Comment by wwarlock** [comment]
I has migrated it by myself for my own project.
Would you interested in it?

**Comment by burtbeckwith** [comment]
Sure, send a pull request and I'll merge that along with another PR that was sent. If you prefer you can send me a zip or tar.gz by email.

**Comment by wwarlock** [comment]
What project version should I assign?

**Comment by burtbeckwith** [comment]
I'll take care of that.

**Comment by xxBedy** [comment]
Tryed @wwarlock version but throws exception when accessing http://localhost:8080/user/search :(

    Line | Method
->>  187 | rethrowRenderException       in /WEB-INF/grails-app/views/layouts/springSecurityUI.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     78 | render                       in     ''
|     67 | renderTemplate . . . . . . . in     ''
|     71 | renderWithinGrailsWebRequest in     ''
|     55 | renderMergedOutputModel . .  in     ''
|    303 | render                       in     ''
|   1244 | render . . . . . . . . . . . in     ''
|   1027 | processDispatchResult        in     ''
|    971 | doDispatch . . . . . . . . . in     ''
|    893 | doService                    in     ''
|    967 | processRequest . . . . . . . in     ''
|    858 | doGet                        in     ''
|    622 | service . . . . . . . . . .  in     ''
|    843 | service                      in     ''
|    729 | service . . . . . . . . . .  in     ''
|    291 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|     52 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|    113 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|     62 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|     53 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|    154 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|    199 | doFilter . . . . . . . . . . in     ''
|     53 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|     65 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|    108 | invoke                       in     ''
|     84 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|    146 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|    295 | doFilterInternal . . . . . . in     ''
|    107 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|    102 | doFilterInternal . . . . . . in     ''
|    107 | doFilter                     in     ''
|    239 | internalDoFilter . . . . . . in     ''
|    206 | doFilter                     in     ''
|    330 | doFilter . . . . . . . . . . in     ''
|    118 | invoke                       in     ''
|     84 | doFilter . . . . . . . . . . in     ''
|    342 | doFilter                     in     ''
|    113 | doFilter . . . . . . . . . . in     ''
|    342 | doFilter                     in     ''
|     53 | doFilter . . . . . . . . . . in     ''
|    342 | doFilter                     in     ''
|    139 | doFilter . . . . . . . . . . in     ''
|    342 | doFilter                     in     ''
|    154 | doFilter . . . . . . . . . . in     ''
|    342 | doFilter                     in     ''
|    199 | doFilter . . . . . . . . . . in     ''
|     53 | doFilter                     in     ''
|    342 | doFilter . . . . . . . . . . in     ''
|     62 | doFilter                     in     ''
|    342 | doFilter . . . . . . . . . . in     ''
|     87 | doFilter                     in     ''
|    342 | doFilter . . . . . . . . . . in     ''
|    192 | doFilterInternal             in     ''
|    160 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|     73 | doFilterInternal             in     ''
|    107 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|     67 | doFilterInternal             in     ''
|    107 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|     85 | doFilterInternal             in     ''
|    107 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|     69 | doFilterInternal             in     ''
|    107 | doFilter . . . . . . . . . . in     ''
|    239 | internalDoFilter             in     ''
|    206 | doFilter . . . . . . . . . . in     ''
|    219 | invoke                       in     ''
|    106 | invoke . . . . . . . . . . . in     ''
|    502 | invoke                       in     ''
|    142 | invoke . . . . . . . . . . . in     ''
|     79 | invoke                       in     ''
|     88 | invoke . . . . . . . . . . . in     ''
|    518 | service                      in     ''
|   1091 | process . . . . . . . . . .  in     ''
|    673 | process                      in     ''
|   1526 | doRun . . . . . . . . . . .  in     ''
|   1482 | run                          in     ''
|   1142 | runWorker . . . . . . . . .  in     ''
|    617 | run                          in     ''
|     61 | run . . . . . . . . . . . .  in     ''
^    745 | run                          in     ''

Caused by GroovyPagesException: Error processing GroovyPageView: [views/layouts/springSecurityUI.gsp:15] Error executing tag <s2ui:resources>: No such property: jqui for class: grails.plugin.springsecurity.ui.SecurityUiTagLib
Possible solutions: s2ui, out
->>   15 | createGroovyPageException    in /WEB-INF/grails-app/views/layouts/springSecurityUI.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by GrailsTagException: [views/layouts/springSecurityUI.gsp:15] Error executing tag <s2ui:resources>: No such property: jqui for class: grails.plugin.springsecurity.ui.SecurityUiTagLib
Possible solutions: s2ui, out
->>   15 | doCall                       in views/layouts/springSecurityUI.gsp
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Caused by MissingPropertyException: No such property: jqui for class: grails.plugin.springsecurity.ui.SecurityUiTagLib
Possible solutions: s2ui, out
->>  156 | propertyMissing              in grails.artefact.TagLibrary$Trait$Helper
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     36 | doCall                       in grails.plugin.springsecurity.ui.SecurityUiTagLib$_closure1
|     33 | doCall . . . . . . . . . . . in gsp_grails_spring_security_ui_layoutsspringSecurityUI_gsp$_run_closure1
|     48 | run                          in gsp_grails_spring_security_ui_layoutsspringSecurityUI_gsp
|     62 | doFilter . . . . . . . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|     53 | doFilter                     in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     62 | doFilter . . . . . . . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1142 | runWorker                    in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                          in java.lang.Thread

**Comment by wwarlock** [comment]
Thanks, @xxBeddy, I'll investigate this soon.

**Comment by codeconsole** [comment]
@xxBedy  I converted this plugin to Grails 3 a while ago.
https://github.com/grails-plugins/grails-spring-security\ui/pull/33
Mine has been working flawlessly in a live environment for over 4 months.

**Comment by burtbeckwith** [comment]
Fixed in 3.0.0.M1
