### ISSUE TITLE
Failing with no user message, when trying to register with an existing email address

### ISSUE THREAD

**Issue by pjdvmalan** [grails-plugins/grails-spring-security-ui#48]
When trying to register with an existing username, 'Username exist' error is correctly thrown. If you try to register with a unique username, but an email that already exist, no error is displayed to the end-user.

**Comment by ddelponte** [comment]
Hi @pjdvmalan and thank you for submitting this issue!

This is not a bug and is working as expected.

By default, the user's email address is not stored in the database.  Because it's not stored in the database, we have no way of checking for duplicates.

Here's a link to the code within the command object that queries the database for duplicate users:
https://github.com/grails-plugins/grails-spring-security-ui/blob/master/plugin/grails-app/controllers/grails/plugin/springsecurity/ui/RegisterController.groovy#L272

And, please also notice, there is no `email` associated with the user domain class so no checking of duplicates can be done.

Here's a link to the template used to generate the user domain class:
https://github.com/grails-plugins/grails-spring-security-core/blob/master/plugin/src/main/templates/Person.groovy.template

I will mark this as "Not a bug" and close

**Comment by pjdvmalan** [comment]
Thank you for your feedback. Much appreciated & noted.

I guess that the issue arise from the following in the documentation:
> RegisterController and its GSPs assume that your User domain class has an email field. Be sure to either rework the workflow (using the s2ui-override script) if you don’t need an email confirmation step or add an email field.

Some of the functionality/flow depends on an email adres presend - I am going on the principle that people do sometimes forget their password.

This may be something to be considered int the architecture going forward ... detect if an email is defined. If so - check for duplication.

Just a suggestion.

**Comment by ddelponte** [comment]
> This may be something to be considered int the architecture going forward ... detect if an email is defined. If so - check for duplication.

Thanks @pjdvmalan ! 

Would you be so kind as to submit your suggested improvement as a new issue?
