### ISSUE TITLE
postResetUrl not working

### ISSUE THREAD

**Issue by rpalcolea** [grails-plugins/grails-spring-security-ui#60]
Documentation suggests to use `grails.plugin.springsecurity.ui.forgotPassword.postResetUrl` in order to set the URL after a password reset. For example:

``` groovy
----
grails.plugin.springsecurity.ui.forgotPassword.postResetUrl = '/reset'
----
```

In `RegisterController` the `registerPostResetUrl` variable looks for `conf.ui.register.postResetUrl` which should be `conf.ui.forgotPassword.postResetUrl`.

https://github.com/grails-plugins/grails-spring-security-ui/blob/master/grails-app/controllers/grails/plugin/springsecurity/ui/RegisterController.groovy#L212

**Comment by ddelponte** [comment]
@rpalcolea thank-you for creating this issue!

I saw you had a PR (https://github.com/grails-plugins/grails-spring-security-ui/pull/61) out there with the desired changes, but I'm unable to merge because of conflicts.

As a result, I've chosen to create a separate PR(https://github.com/grails-plugins/grails-spring-security-ui/pull/78) without the conflicts:

You may choose to:
1. resolve conflicts in your original PR so we may merge it 
or
2. close your PR and we'll merge the one I created

✨

**Comment by ddelponte** [comment]
Resolved!  
This has been fixed by PR:
https://github.com/grails-plugins/grails-spring-security-ui/pull/78
